export const SET_TODOS_DATA = 'todos/setData'
export const UPDATE_TODOS_DATA = 'todos/updateData'
export const SET_TODOS_DATA_IIEM = 'todos/setDataItem'
export const SET_TODOS_LOADING = 'todos/setLoading'
export const SET_TODOS_ERROR = 'todos/setError'
